// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp9I67erH5p86cXxpUXkB8UbeOjuMb7ts',
    appId: '1:38502725467:web:3135b3edc36832a79dcc7e',
    messagingSenderId: '38502725467',
    projectId: 'chatapp1-d07cc',
    authDomain: 'chatapp1-d07cc.firebaseapp.com',
    storageBucket: 'chatapp1-d07cc.appspot.com',
    measurementId: 'G-W2Y9TDHR0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7WAzu2WTPnICZ8z6EY9wJbCbLX_3NxNk',
    appId: '1:38502725467:android:fb00eacb008d1dc99dcc7e',
    messagingSenderId: '38502725467',
    projectId: 'chatapp1-d07cc',
    storageBucket: 'chatapp1-d07cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9j9kcJC-vPam_a80SbBRC5Zbzu-73OAQ',
    appId: '1:38502725467:ios:24f8c6d3a96f6c7d9dcc7e',
    messagingSenderId: '38502725467',
    projectId: 'chatapp1-d07cc',
    storageBucket: 'chatapp1-d07cc.appspot.com',
    iosBundleId: 'com.example.chatapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9j9kcJC-vPam_a80SbBRC5Zbzu-73OAQ',
    appId: '1:38502725467:ios:24f8c6d3a96f6c7d9dcc7e',
    messagingSenderId: '38502725467',
    projectId: 'chatapp1-d07cc',
    storageBucket: 'chatapp1-d07cc.appspot.com',
    iosBundleId: 'com.example.chatapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp9I67erH5p86cXxpUXkB8UbeOjuMb7ts',
    appId: '1:38502725467:web:005ff6eab712877c9dcc7e',
    messagingSenderId: '38502725467',
    projectId: 'chatapp1-d07cc',
    authDomain: 'chatapp1-d07cc.firebaseapp.com',
    storageBucket: 'chatapp1-d07cc.appspot.com',
    measurementId: 'G-SH8J5GR3MR',
  );
}
